package com.examples.apps.core.model;

// Generated 17-ago-2014 11:49:39 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Review generated by hbm2java
 */
public class Review implements java.io.Serializable {

	private String revId;
	private User user;
	private String revTitle;
	private String revText;
	private BigDecimal revRating;
	private Date revCreationDatetime;

	public Review() {
	}

	public Review(String revId, User user, String revTitle,
			BigDecimal revRating, Date revCreationDatetime) {
		this.revId = revId;
		this.user = user;
		this.revTitle = revTitle;
		this.revRating = revRating;
		this.revCreationDatetime = revCreationDatetime;
	}

	public Review(String revId, User user, String revTitle, String revText,
			BigDecimal revRating, Date revCreationDatetime) {
		this.revId = revId;
		this.user = user;
		this.revTitle = revTitle;
		this.revText = revText;
		this.revRating = revRating;
		this.revCreationDatetime = revCreationDatetime;
	}

	public String getRevId() {
		return this.revId;
	}

	public void setRevId(String revId) {
		this.revId = revId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRevTitle() {
		return this.revTitle;
	}

	public void setRevTitle(String revTitle) {
		this.revTitle = revTitle;
	}

	public String getRevText() {
		return this.revText;
	}

	public void setRevText(String revText) {
		this.revText = revText;
	}

	public BigDecimal getRevRating() {
		return this.revRating;
	}

	public void setRevRating(BigDecimal revRating) {
		this.revRating = revRating;
	}

	public Date getRevCreationDatetime() {
		return this.revCreationDatetime;
	}

	public void setRevCreationDatetime(Date revCreationDatetime) {
		this.revCreationDatetime = revCreationDatetime;
	}

}
