package com.examples.apps.core.model;

// Generated 17-ago-2014 11:49:39 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String usrId;
	private String usrNickname;
	private String usrEmail;
	private String usrPassword;
	private String usrName;
	private Date usrBirthdate;
	private Set reviews = new HashSet(0);

	public User() {
	}

	public User(String usrId, String usrNickname, String usrEmail,
			String usrPassword, String usrName, Date usrBirthdate) {
		this.usrId = usrId;
		this.usrNickname = usrNickname;
		this.usrEmail = usrEmail;
		this.usrPassword = usrPassword;
		this.usrName = usrName;
		this.usrBirthdate = usrBirthdate;
	}

	public User(String usrId, String usrNickname, String usrEmail,
			String usrPassword, String usrName, Date usrBirthdate, Set reviews) {
		this.usrId = usrId;
		this.usrNickname = usrNickname;
		this.usrEmail = usrEmail;
		this.usrPassword = usrPassword;
		this.usrName = usrName;
		this.usrBirthdate = usrBirthdate;
		this.reviews = reviews;
	}

	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	public String getUsrNickname() {
		return this.usrNickname;
	}

	public void setUsrNickname(String usrNickname) {
		this.usrNickname = usrNickname;
	}

	public String getUsrEmail() {
		return this.usrEmail;
	}

	public void setUsrEmail(String usrEmail) {
		this.usrEmail = usrEmail;
	}

	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	public Date getUsrBirthdate() {
		return this.usrBirthdate;
	}

	public void setUsrBirthdate(Date usrBirthdate) {
		this.usrBirthdate = usrBirthdate;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

}
